name: SonarQube Analysis

on:
  push:
    branches:
      - dev

jobs:
  sonarqube:
    name: SonarQube Scanner
    runs-on: self-hosted  # your self-hosted runner with Java and SonarScanner installed

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Run SonarQube Analysis
        run: |
          /home/hafsa/sonar-scanner/bin/sonar-scanner \
            -Dsonar.projectKey=react-shopping-cart \
            -Dsonar.sources=src \
            -Dsonar.exclusions=**/node_modules/**,**/*.test.tsx,**/*.test.js \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.branch.name=${{ github.ref_name }}
